apiVersion: v1
kind: ConfigMap
metadata:
  name: zwiftfetcher-config
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.Production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "{{ .Values.logging.level.default }}",
          "Microsoft.Hosting.Lifetime": "{{ .Values.logging.level.microsoft }}",
          "Microsoft.EntityFrameworkCore": "{{ .Values.logging.level.entityFramework }}"
        }
      },
      "ConnectionStrings": {
        "kafka": "{{ .Values.kafka.bootstrapServers }}",
        "redis": "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
      },
      "ZwiftFetcherOptions": {
        "InstanceId": "{{ .Values.zwiftFetcher.config.instanceId }}",
        "HeartbeatIntervalMinutes": {{ .Values.shared.heartbeatIntervalMinutes }},
        "PollIntervalMinutes": {{ .Values.shared.pollIntervalMinutes }},
        "LookbackDays": {{ .Values.shared.lookbackDays }},
        "DeadThresholdMinutes": {{ .Values.shared.deadThresholdMinutes }},
        "MaxPendingActivities": {{ .Values.shared.maxPendingActivities }},
        "MaxParallelUsers": {{ .Values.shared.maxParallelUsers }},
        "MaxParallelActivities": {{ .Values.shared.maxParallelActivities }},
        "MaxSequentialCredentialFailures": {{ .Values.shared.maxSequentialCredentialFailures }},
        "AuthUrl": "{{ .Values.zwiftFetcher.config.zwift.authUrl }}",
        "BaseUrl": "{{ .Values.zwiftFetcher.config.zwift.baseUrl }}",
        "ClientId": "{{ .Values.zwiftFetcher.config.zwift.clientId }}",
        "ClientSecret": "{{ .Values.zwiftFetcher.config.zwift.clientSecret }}",
        "AmazonS3RateLimit": {{ .Values.zwiftFetcher.config.zwift.amazonS3RateLimit }},
        "ZwfitApiRateLimit": {{ .Values.zwiftFetcher.config.zwift.zwfitApiRateLimit }}
      },
      "AllowedHosts": "*"
    }
