apiVersion: v1
kind: PersistentVolume
metadata:
  name: whoop-blobs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/kaleba/whoop-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whoop-blobs-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: whoop-blobs-pv
  resources:
    requests:
      storage: 5Gi
