apiVersion: v1
kind: PersistentVolume
metadata:
  name: workout-files-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/kaleba/workout-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workout-files-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: workout-files-pv
  resources:
    requests:
      storage: 1Gi
