{{- if .Values.gui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.gui.replicas }}
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: {{ .Values.imageRegistry }}/{{ .Values.gui.image }}:{{ .Values.gui.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.gui.resources | nindent 10 }}
{{- end }}
