apiVersion: v1
kind: ConfigMap
metadata:
  name: uploader-config
  namespace: {{ .Values.global.namespace }}
data:
  appsettings.Production.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "{{ .Values.logging.level.default }}",
          "Microsoft.Hosting.Lifetime": "{{ .Values.logging.level.microsoft }}",
          "Microsoft.EntityFrameworkCore": "{{ .Values.logging.level.entityFramework }}"
        }
      },
      "ConnectionStrings": {
        "kafka": "{{ .Values.kafka.bootstrapServers }}"
      },
      "GarminUploaderOptions": {
        "InstanceId": "{{ .Values.uploader.config.instanceId }}",
        "HeartbeatIntervalMinutes": {{ .Values.uploader.config.heartbeatIntervalMinutes }},
        "MaxRetries": {{ .Values.uploader.config.maxRetries }},
        "OrphanThresholdMinutes": {{ .Values.uploader.config.orphanThresholdMinutes }}
      }
    }
